sign-commit = true
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]", replace = "[{{version}}] - {{date}}" }
]
pre-release-hook = ["cargo", "make", "prepare-release"]
